create table if not exists public.staff_accounts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  auth_user_id uuid null
);

alter table public.staff_accounts
  add column if not exists phone text,
  add column if not exists display_name text,
  add column if not exists login_email text,
  add column if not exists permissions jsonb not null default '{}'::jsonb,
  add column if not exists is_active boolean not null default true,
  add column if not exists session_enabled boolean not null default true,
  add column if not exists session_minutes integer not null default 60,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists staff_accounts_phone_idx on public.staff_accounts(phone);
create index if not exists staff_accounts_auth_user_idx on public.staff_accounts(auth_user_id);

create or replace function public.touch_staff_accounts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists staff_accounts_updated_at on public.staff_accounts;
create trigger staff_accounts_updated_at
before update on public.staff_accounts
for each row execute function public.touch_staff_accounts_updated_at();

alter table public.staff_accounts enable row level security;
