-- Customer self-service requests: reviewable by Admin only.
-- This migration does not change existing orders, stock, money, or Bosta deliveries.
begin;

create table if not exists public.order_customer_requests (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  request_type text not null check (request_type in ('cancel', 'edit')),
  reason text not null check (char_length(btrim(reason)) between 5 and 1000),
  requested_changes jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'applied')),
  admin_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists order_customer_requests_order_id_idx
  on public.order_customer_requests (order_id, created_at desc);

create index if not exists order_customer_requests_status_idx
  on public.order_customer_requests (status, created_at desc);

alter table public.order_customer_requests enable row level security;

revoke all on table public.order_customer_requests from anon, authenticated;

commit;
