-- Safe archive workflow for products, complaints and affected Bosta orders.
-- No existing product, complaint, order, stock or shipment is changed by this migration.

alter table public.products
  add column if not exists is_archived boolean not null default false,
  add column if not exists archived_at timestamptz,
  add column if not exists archived_by text,
  add column if not exists archive_reason text;

alter table public.complaints
  add column if not exists is_archived boolean not null default false,
  add column if not exists archived_at timestamptz,
  add column if not exists archived_by text,
  add column if not exists archive_reason text;

alter table public.orders
  add column if not exists bosta_sync_status text not null default 'not_required',
  add column if not exists bosta_cancelled_at timestamptz,
  add column if not exists bosta_cancel_reason text,
  add column if not exists bosta_cancel_error text,
  add column if not exists bosta_pickup_id text,
  add column if not exists bosta_pickup_cancelled_at timestamptz,
  add column if not exists bosta_pickup_cancel_error text;

create table if not exists public.archive_events (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('product', 'complaint', 'order')),
  entity_id bigint not null,
  action text not null check (action in ('archive', 'restore', 'bosta_cancel')),
  reason text not null check (char_length(btrim(reason)) between 5 and 1000),
  actor_user_id text,
  actor_name text,
  bosta_sync_status text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists archive_events_entity_idx
  on public.archive_events (entity_type, entity_id, created_at desc);

create index if not exists products_archive_idx
  on public.products (is_archived, archived_at desc);

create index if not exists complaints_archive_idx
  on public.complaints (is_archived, archived_at desc);

alter table public.archive_events enable row level security;
revoke all on table public.archive_events from anon, authenticated;

-- Existing rows remain visible to the Admin service-role query until archived.
update public.products set is_archived = false where is_archived is null;
update public.complaints set is_archived = false where is_archived is null;
