-- طلبات مساعدة الموظفين وردود المالك.
-- تُنفذ يدوياً في Supabase SQL Editor بعد مراجعة المالك.
begin;

create table if not exists public.staff_help_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  staff_id bigint null references public.staff_accounts(id) on delete set null,
  staff_auth_user_id uuid null,
  staff_name text not null,
  staff_phone text null,
  subject text not null,
  message text not null,
  status text not null default 'pending' check (status in ('pending', 'replied', 'closed')),
  owner_reply text null,
  owner_reply_image_url text null,
  replied_by uuid null,
  replied_at timestamptz null,
  read_at timestamptz null
);

create index if not exists staff_help_requests_staff_idx
  on public.staff_help_requests(staff_auth_user_id, created_at desc);
create index if not exists staff_help_requests_status_idx
  on public.staff_help_requests(status, created_at desc);

create or replace function public.touch_staff_help_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists staff_help_requests_updated_at on public.staff_help_requests;
create trigger staff_help_requests_updated_at
before update on public.staff_help_requests
for each row execute function public.touch_staff_help_requests_updated_at();

alter table public.staff_help_requests enable row level security;

-- لا توجد سياسات عامة؛ القراءة والكتابة تتم من endpoint محمي بالجلسة وبـservice role.
do $$
declare
  item text := 'staff_help_requests';
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = item
     ) then
    execute format('alter publication supabase_realtime add table public.%I', item);
  end if;
exception when undefined_object then
  raise notice 'supabase_realtime publication is not available yet.';
end $$;

commit;
