-- إشعارات داخل لوحة الإدارة واشتراكات Web Push للأجهزة.
-- لا توجد سياسات عامة؛ كل القراءة والكتابة تتم من endpoint محمي بـservice role.
begin;

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  title text not null,
  body text not null,
  url text null,
  required_permission text null,
  required_permissions text[] not null default '{}'::text[],
  recipient_user_id uuid null,
  recipient_scope text not null default 'permission' check (recipient_scope in ('permission','all_admins','user')),
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz null,
  expires_at timestamptz null
);

create index if not exists admin_notifications_created_idx
  on public.admin_notifications(created_at desc);
create index if not exists admin_notifications_recipient_idx
  on public.admin_notifications(recipient_user_id, created_at desc);
create index if not exists admin_notifications_permission_idx
  on public.admin_notifications(required_permission, created_at desc);

create table if not exists public.admin_notification_reads (
  notification_id bigint not null references public.admin_notifications(id) on delete cascade,
  user_id uuid not null,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);

create index if not exists admin_notification_reads_user_idx
  on public.admin_notification_reads(user_id, read_at desc);

create table if not exists public.admin_push_subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid not null,
  is_owner boolean not null default false,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text null,
  is_active boolean not null default true,
  unique (user_id, endpoint)
);

create index if not exists admin_push_subscriptions_user_idx
  on public.admin_push_subscriptions(user_id, is_active);

create or replace function public.touch_admin_push_subscriptions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_push_subscriptions_updated_at on public.admin_push_subscriptions;
create trigger admin_push_subscriptions_updated_at
before update on public.admin_push_subscriptions
for each row execute function public.touch_admin_push_subscriptions_updated_at();

alter table public.admin_notifications enable row level security;
alter table public.admin_notification_reads enable row level security;
alter table public.admin_push_subscriptions enable row level security;

-- لا توجد سياسات عامة؛ الوصول يتم من Admin API بعد التحقق من الجلسة والصلاحية.
do $$
declare
  item text;
begin
  foreach item in array array['admin_notifications','admin_notification_reads','admin_push_subscriptions'] loop
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (
         select 1 from pg_publication_tables
         where pubname = 'supabase_realtime'
           and schemaname = 'public'
           and tablename = item
       ) then
      execute format('alter publication supabase_realtime add table public.%I', item);
    end if;
  end loop;
exception when undefined_object then
  raise notice 'supabase_realtime publication is not available yet.';
end $$;

commit;
