-- Phase 3: staff profile/password approvals and storefront contact coordinates
create table if not exists public.profile_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  staff_id bigint not null references public.staff_accounts(id) on delete cascade,
  request_type text not null default 'password_change' check (request_type in ('password_change')),
  reason text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  admin_reason text,
  reviewed_by text,
  reviewed_at timestamptz
);
create index if not exists profile_requests_staff_idx on public.profile_requests(staff_id, created_at desc);
create index if not exists profile_requests_status_idx on public.profile_requests(status, created_at desc);

alter table public.site_settings add column if not exists map_latitude numeric(10,7);
alter table public.site_settings add column if not exists map_longitude numeric(10,7);
alter table public.site_settings add column if not exists footer_phone_visible boolean not null default true;
alter table public.site_settings add column if not exists whatsapp_visible boolean not null default true;

alter table public.profile_requests enable row level security;
drop policy if exists "profile requests service role only" on public.profile_requests;
create policy "profile requests service role only" on public.profile_requests
  using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
